image: $CI_REGISTRY/vlasami6/fmltest:master

test:
  script:
    - meson setup build -D b_sanitize=address,undefined
    - meson compile -C build
    - cppcheck --error-exitcode=1 src/*.c
    - export FML="$(readlink -f ./build/fml)"
    #- export FML_REF=/cfml/fml
    - /FMLtest/suite all
